x-logging: &logging
  logging:
    driver: loki
    options:
      loki-url: "http://localhost:3100/loki/api/v1/push"
      loki-batch-size: 50
      loki-max-backoff: 800ms
      loki-retries: 2 

services:

  gather:
    <<: *logging
    build: ./gather
    depends_on:
     - graphite
     - loki

  graphite:
    image: graphiteapp/graphite-statsd
    volumes:
      - graphite-storage:/opt/graphite/storage

  loki:
    image: grafana/loki
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "127.0.0.1:3100:3100"

  grafana:
    build: ./grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana


volumes:
  graphite-storage:
  grafana-storage:
